version: '3'

services:

  server:
    container_name: server
    build: 
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
    volumes:
      - ./www:/var/www
      - ./docker/server/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/server/php.ini:/usr/local/etc/php/php.ini

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@sa
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
    volumes:
      - ./db/mssql/data:/var/opt/mssql/data
      - ./db/mssql/log:/var/opt/mssql/log
      - ./db/mssql/secrets:/var/opt/mssql/secrets